parameters:

    # controllers

    bc_app_wallet_address.index_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Address\Index
    bc_app_wallet_address.show_new_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Address\ShowNew
    bc_app_wallet_address.create_controller.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Controller\Address\Generate

    # sercice facades

    # services

    # repositories

    bc_app_wallet_address.encrypted_address_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelEncryptedAddressRepository
    bc_app_wallet_address.address_repository.class: BlockCypher\AppWallet\Infrastructure\Persistence\Flywheel\FlywheelAddressRepository

    
    # command handlers

    bc_app_wallet_address.create_address_command_handler.class: BlockCypher\AppWallet\App\Command\CreateAddressCommandHandler

    # form factories

    bc_app_wallet_address.address_form_factory.class: BlockCypher\AppWallet\Infrastructure\AppWalletBundle\Form\Address\AddressFormFactory

services:

    # controllers

    bc_app_wallet_address.index_controller:
        class: %bc_app_wallet_address.index_controller.class%
        arguments:
         - @templating
         - @translator
         - @session
         - @bc_app_wallet_wallet.wallet_service_facade

    bc_app_wallet_address.show_new_controller:
        class: %bc_app_wallet_address.show_new_controller.class%
        arguments:
         - @templating
         - @translator
         - @session
         - @bc_app_wallet_address.address_form_factory
         - @bc_app_wallet_wallet.wallet_service_facade

    bc_app_wallet_address.create_controller:
        class: %bc_app_wallet_address.create_controller.class%
        arguments:
         - @templating
         - @translator
         - @session
         - @router
         - @bc_app_wallet_address.address_form_factory
         - @command_bus
         - @bc_app_wallet_wallet.wallet_service_facade

    # sercice facades

    # services
    
    # repositories

    bc_app_wallet_address.encrypted_address_repository:
        class: %bc_app_wallet_address.encrypted_address_repository.class%
        arguments:
          - "%kernel.logs_dir%/../data"

    bc_app_wallet_address.address_repository:
        class: %bc_app_wallet_address.address_repository.class%
        arguments:
          - @bc_app_wallet_address.encrypted_address_repository
          - @bc_app_common_infrastructure_app_common.encryptor
          - @bc_app_common_infrastructure_app_common.encryptor
    
    # command handlers

    bc_app_wallet_address.create_address_command_handler:
        class: %bc_app_wallet_address.create_address_command_handler.class%
        arguments:
            - @bc_app_wallet_wallet.wallet_repository
            - @bc_app_wallet_address.address_repository
            - @bc_app_common_blockcypher.wallet_service
            - @bc_app_common_infrastructure_app_common.clock
        tags:
            - { name: command_handler, handles: bc_app_wallet_address_create_address }

    # form factory

    bc_app_wallet_address.address_form_factory:
        class: "%bc_app_wallet_address.address_form_factory.class%"
        public: false
        arguments:
            - @form.factory
            - @router
            - @translator
            - @bc_app_wallet_wallet.wallet_repository